import type { CatalogItemInput } from "../schema";
import { A } from "./_rules";

const base = {
  family: "CLAW",
  runtime: "openclaw",
  modelPolicies: ["balanced", "local-first", "customer-provider"],
  compute: ["cpu", "unified-memory-node"],
  deployments: ["managed-cell", "private-cloud"],
  maturity: "CONFIGURABLE",
} as const satisfies Partial<CatalogItemInput>;

export const CLAW_ITEMS: CatalogItemInput[] = [
  {
    ...base,
    slug: "chief-of-staff",
    name: "Chief of Staff",
    foundation: "chief",
    summary: "A persistent assistant that prepares your day, tracks commitments and keeps a decision log you can search later.",
    description:
      "Chief of Staff reads your calendar, inbox and task lists each morning and writes a short briefing: what is due, who is waiting on you and which meetings need preparation. It keeps a running decision log with links back to the source message, drafts follow-ups for you to approve, and never sends or accepts anything on your behalf without a recorded approval.",
    outcomes: [
      "A written morning briefing before your first meeting",
      "Commitments from email and meetings captured as tracked follow-ups",
      "A searchable decision log with links to the original source",
      "Follow-up drafts queued for one-tap approval",
    ],
    integrations: ["Google Workspace", "Microsoft 365", "Slack", "Notion", "Linear"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.deleteDeny, A.adminDeny],
    profile: "OPERATOR",
    tags: ["briefing", "follow-up", "executive"],
  },
  {
    ...base,
    slug: "executive-inbox",
    name: "Executive Inbox Assistant",
    foundation: "chief",
    summary: "Triage a busy inbox into decide, delegate, reply and archive — with replies drafted in your voice and held for approval.",
    description:
      "The Executive Inbox Assistant sorts incoming mail by what it needs from you, drafts replies that follow your tone guide and flags anything with money, legal terms or unknown senders. Message content is treated as untrusted data: instructions inside an email never change what the assistant is allowed to do. Nothing leaves your mailbox until you approve it.",
    outcomes: [
      "Inbox sorted into decide, delegate, reply and archive",
      "Reply drafts in your tone, held until you approve",
      "Payment, contract and unknown-sender messages flagged for review",
    ],
    integrations: ["Gmail", "Outlook", "Slack"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.deleteApproval, A.adminDeny],
    profile: "SAFE",
    tags: ["email", "triage"],
  },
  {
    ...base,
    slug: "meeting-follow-through",
    name: "Meeting Prep & Follow-Through",
    foundation: "chief",
    summary: "Briefs you before each meeting and turns the notes afterwards into owners, dates and drafted recaps.",
    description:
      "Before a meeting it assembles the relevant threads, documents and open items into a one-page brief. Afterwards it turns notes or transcripts into action items with owners and due dates, drafts the recap for the attendees and keeps checking until each item is closed. Recaps are sent only after you approve them.",
    outcomes: [
      "A one-page brief for every meeting on your calendar",
      "Action items with owners and dates extracted from notes",
      "Recap emails drafted for approval, not sent automatically",
    ],
    integrations: ["Google Calendar", "Outlook Calendar", "Zoom", "Google Docs", "Notion"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.adminDeny],
    profile: "SAFE",
    tags: ["meetings", "action-items"],
  },
  {
    ...base,
    slug: "research-desk",
    name: "Research Desk",
    foundation: "research",
    summary: "A research assistant with a persistent source library, so every answer comes with citations you can open and check.",
    description:
      "Research Desk keeps a library of the sources you and it have gathered — papers, filings, web pages and internal documents — and answers questions with citations to specific passages. Web content is handled as untrusted data. It tracks which claims are well supported and which rest on a single source, and it remembers corrections you make.",
    outcomes: [
      "Answers with citations to the exact passage used",
      "A reusable, searchable source library per project",
      "Weakly supported claims marked as such",
      "Corrections you make are remembered with their provenance",
    ],
    integrations: ["Web search", "Google Drive", "Zotero", "SharePoint"],
    actions: [A.read, A.draft, A.write, A.sendDeny, A.adminDeny],
    profile: "SAFE",
    tags: ["citations", "sources", "analysis"],
  },
  {
    ...base,
    slug: "support-desk-assistant",
    name: "Support Desk Assistant",
    foundation: "support",
    summary: "Drafts accurate replies from your help centre and past tickets, and escalates anything outside policy to a person.",
    description:
      "The Support Desk Assistant reads each new ticket, finds the relevant help-centre articles and similar resolved tickets, and drafts a reply for an agent to approve. Refunds, account changes and anything outside your written policy are escalated rather than answered. Customer messages are treated as untrusted input.",
    outcomes: [
      "Reply drafts grounded in your help centre and resolved tickets",
      "Policy-sensitive requests escalated with a summary",
      "Consistent tone across agents and shifts",
    ],
    integrations: ["Zendesk", "Intercom", "Freshdesk", "Help Scout"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.spendDeny, A.adminDeny],
    profile: "SAFE",
    tags: ["tickets", "customer-service"],
  },
  {
    ...base,
    slug: "sales-desk-assistant",
    name: "Sales Desk Assistant",
    foundation: "crm-sales",
    summary: "Keeps your CRM current from email and calls, and drafts next-step outreach for each open deal.",
    description:
      "It reads your sales conversations, updates contact and deal records with what actually happened, and suggests the next step for every open opportunity. Outreach is drafted for you to edit and approve; bulk sends are capped per hour and never go to unverified recipients.",
    outcomes: [
      "CRM records updated from real conversations",
      "A next step suggested for every open deal",
      "Outreach drafts with per-hour send limits",
    ],
    integrations: ["HubSpot", "Salesforce", "Pipedrive", "Gmail", "Outlook"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.deleteDeny, A.adminDeny],
    profile: "OPERATOR",
    tags: ["crm", "pipeline", "outreach"],
  },
  {
    ...base,
    slug: "operations-coordinator",
    name: "Operations Coordinator",
    foundation: "operations",
    summary: "Runs recurring checklists, chases handoffs between teams and raises exceptions before they become incidents.",
    description:
      "The Operations Coordinator owns your recurring operational rhythms: opening and closing checklists, shift handoffs, weekly reviews. It notices when a step is late or skipped, asks the responsible person, and escalates exceptions with context. Schedule changes affecting people outside your organisation require approval.",
    outcomes: [
      "Recurring checklists run and tracked to completion",
      "Late or skipped steps chased automatically",
      "Exceptions escalated with the context needed to act",
    ],
    integrations: ["Slack", "Microsoft Teams", "Asana", "Google Sheets"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.adminDeny],
    profile: "OPERATOR",
    tags: ["checklists", "handoffs"],
  },
  {
    ...base,
    slug: "bookkeeping-assistant",
    name: "Bookkeeping Assistant",
    foundation: "finance-admin",
    summary: "Categorises transactions, prepares reconciliation drafts and chases missing receipts — and never moves money.",
    description:
      "The Bookkeeping Assistant proposes categories for new transactions, matches receipts, drafts reconciliation notes for your accountant and chases missing paperwork. It has no ability to pay, transfer or approve spending; those actions are denied at the policy level, not just hidden in the interface.",
    outcomes: [
      "Transactions categorised with a reason for each suggestion",
      "Missing receipts chased on a schedule",
      "Reconciliation drafts ready for accountant review",
    ],
    integrations: ["QuickBooks", "Xero", "Google Drive", "Dext"],
    actions: [A.read, A.draft, A.writeApproval, A.sendApproval, A.spendDeny, A.deleteDeny, A.adminDeny],
    profile: "SAFE",
    modelPolicies: ["local-first", "customer-provider"],
    tags: ["accounting", "receipts"],
  },
  {
    ...base,
    slug: "developer-workspace",
    name: "Developer Workspace Assistant",
    foundation: "developer-builder",
    summary: "A coding assistant in an isolated workspace: it can branch, edit and run tests, but merging and deploying need you.",
    description:
      "The Developer Workspace Assistant works inside a bounded copy of your repository with an allowlist of commands. It can read code, open branches, make edits and run your test suite in a sandbox. Merging, publishing packages and deploying are approval-gated, and it cannot reach hosts or paths outside its allowlist.",
    outcomes: [
      "Changes proposed on branches with passing tests",
      "Commands limited to an explicit allowlist",
      "Merges and deploys only after human approval",
    ],
    integrations: ["GitHub", "GitLab", "Linear", "Jira"],
    actions: [A.read, A.draft, A.write, A.publishApproval, A.deployApproval, A.deleteApproval, A.adminDeny],
    profile: "OPERATOR",
    compute: ["cpu", "gpu-24gb", "unified-memory-node"],
    tags: ["code", "tests", "sandbox"],
  },
  {
    ...base,
    slug: "team-memory",
    name: "Team Memory",
    foundation: "knowledge-memory",
    summary: "Shared organisational memory that records where each fact came from and keeps a history of corrections.",
    description:
      "Team Memory captures decisions, definitions and how-tos from the places your team already works. Every memory keeps its provenance — who said it, where and when — and corrections are stored as new versions rather than silent overwrites. Retention rules and export are built in, and secrets are rejected before they can be stored.",
    outcomes: [
      "Answers that cite the conversation or document they came from",
      "Corrections tracked as versions, never silent overwrites",
      "Retention rules and full export per workspace",
    ],
    integrations: ["Slack", "Confluence", "Notion", "Google Drive"],
    actions: [A.read, A.draft, A.write, A.deleteApproval, A.adminDeny],
    profile: "SAFE",
    tags: ["memory", "provenance", "wiki"],
  },
  {
    ...base,
    slug: "household-organizer",
    name: "Household Organizer",
    foundation: "family-play",
    summary: "A family assistant for calendars, chores, meal plans and school notices, with guardian controls on every account.",
    description:
      "Household Organizer merges family calendars, turns school and club notices into dates and checklists, proposes weekly meal plans and shopping lists and keeps chores fair. Guardians control what children's accounts can see and do. Purchases and messages to people outside the household always require a guardian's approval.",
    outcomes: [
      "One family calendar built from every source",
      "School notices turned into dates and checklists",
      "Meal plans and shopping lists drafted weekly",
    ],
    integrations: ["Google Calendar", "Apple Calendar", "Email"],
    actions: [A.read, A.draft, A.write, A.sendApproval, A.spendApproval, A.adminDeny],
    profile: "SAFE",
    modelPolicies: ["local-first", "balanced"],
    deployments: ["managed-cell", "edge-device"],
    compute: ["cpu", "customer-hardware"],
    tags: ["family", "calendar", "guardian"],
  },
  {
    ...base,
    slug: "study-companion",
    name: "Study Companion",
    foundation: "learning-maker",
    summary: "A patient tutor that remembers what you have covered, quizzes you on it and plans the next session.",
    description:
      "Study Companion builds a study plan from your syllabus or goals, explains concepts at the level you ask for, and uses spaced repetition to quiz you on what you have covered. It remembers where you struggled and adjusts. It can run on local models for privacy, and it never submits work on your behalf.",
    outcomes: [
      "A study plan built from your syllabus or goals",
      "Spaced-repetition quizzes on material already covered",
      "Sessions that adapt to where you struggled",
    ],
    integrations: ["Google Classroom", "Anki export", "PDF library"],
    actions: [A.read, A.draft, A.write, A.sendDeny, A.publishDraftOnly, A.adminDeny],
    profile: "SAFE",
    modelPolicies: ["local-first", "local-only", "lowest-cost"],
    deployments: ["managed-cell", "edge-device"],
    compute: ["cpu", "customer-hardware", "unified-memory-node"],
    tags: ["tutor", "spaced-repetition"],
  },
  {
    ...base,
    slug: "brand-studio-assistant",
    name: "Brand Studio Assistant",
    foundation: "marketing-creative",
    summary: "Drafts on-brand copy and briefs from your style guide, and holds everything for review before it is published.",
    description:
      "Brand Studio Assistant learns your voice, vocabulary and visual rules from your brand guide and past work. It drafts posts, product copy, briefs and variations for testing, checks each draft against the guide and explains any deviation. Publishing to any channel requires approval.",
    outcomes: [
      "Drafts checked against your brand guide with explanations",
      "Variations prepared for testing",
      "Nothing published without approval",
    ],
    integrations: ["Figma", "Google Docs", "Buffer", "Webflow", "Notion"],
    actions: [A.read, A.draft, A.write, A.publishApproval, A.adminDeny],
    profile: "SAFE",
    modelPolicies: ["balanced", "maximum-intelligence", "customer-provider"],
    tags: ["brand", "copy", "content"],
  },
];
