import { CATALOG } from "@/domain/catalog";
import { FOUNDATION_LIST } from "@/domain/foundations";
import { COMPUTE_CLASSES, MODEL_POLICIES, RUNTIMES } from "@/domain/registries";

/**
 * Deterministic, idempotent seed SQL generated from the domain registries and
 * seed catalog. Every insert is `on conflict do nothing`, so re-running the
 * seed never overwrites owner edits (maturity, published, registry status, flags).
 */

function lit(v: string | number | boolean | null | undefined): string {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") {
    if (!Number.isFinite(v)) throw new Error("non-finite number in seed");
    return String(v);
  }
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${v.replace(/'/g, "''")}'`;
}

function jsonLit(v: unknown): string {
  return `${lit(JSON.stringify(v))}::jsonb`;
}

function textArray(values: readonly string[]): string {
  return `array[${values.map(lit).join(", ")}]::text[]`;
}

export const DEFAULT_FEATURE_FLAGS: ReadonlyArray<{ key: string; enabled: boolean; description: string }> = [
  { key: "billing_enabled", enabled: false, description: "Accept payments. Also capped by BILLING_ENABLED in the environment." },
  { key: "provisioning_enabled", enabled: false, description: "Allow provisioning jobs to leave BLOCKED. Also capped by PROVISIONING_ENABLED." },
  { key: "custom_intake_enabled", enabled: true, description: "Accept custom build requests from the public /custom form." },
  { key: "configuration_save_enabled", enabled: true, description: "Let signed-in customers save configurator results." },
];

export function generateSeedSql(): string {
  const out: string[] = [
    "-- GENERATED by scripts/generate-seed.ts from src/domain. Do not edit by hand.",
    "-- Idempotent: every insert is ON CONFLICT DO NOTHING so owner edits survive re-seeding.",
    "",
  ];

  out.push("-- foundations");
  FOUNDATION_LIST.forEach((f, i) => {
    out.push(
      `insert into public.foundations (id, name, summary, sort_order) values (${lit(f.id)}, ${lit(f.name)}, ${lit(f.summary)}, ${i}) on conflict (id) do nothing;`,
    );
  });

  out.push("", "-- runtime registry");
  for (const r of Object.values(RUNTIMES)) {
    out.push(
      `insert into public.runtime_registry (id, label, role, status, isolation) values (${lit(r.id)}, ${lit(r.label)}, ${lit(r.role)}, ${lit(r.defaultStatus)}, ${lit(r.isolation)}) on conflict (id) do nothing;`,
    );
  }

  out.push("", "-- model registry (policies)");
  for (const m of Object.values(MODEL_POLICIES)) {
    out.push(
      `insert into public.model_registry (id, label, description, routes, may_incur_managed_cost) values (${lit(m.id)}, ${lit(m.label)}, ${lit(m.description)}, ${textArray(m.routes)}, ${lit(m.mayIncurManagedCost)}) on conflict (id) do nothing;`,
    );
  }

  out.push("", "-- compute registry");
  for (const c of Object.values(COMPUTE_CLASSES)) {
    out.push(
      `insert into public.compute_registry (id, label, description, memory_gb, metering) values (${lit(c.id)}, ${lit(c.label)}, ${lit(c.description)}, ${lit(c.memoryGb)}, ${lit(c.metering)}) on conflict (id) do nothing;`,
    );
  }

  out.push("", "-- feature flags (billing and provisioning start disabled)");
  for (const f of DEFAULT_FEATURE_FLAGS) {
    out.push(
      `insert into public.feature_flags (key, enabled, description) values (${lit(f.key)}, ${lit(f.enabled)}, ${lit(f.description)}) on conflict (key) do nothing;`,
    );
  }

  out.push("", `-- catalog (${CATALOG.length} items)`);
  for (const item of CATALOG) {
    const { evidence, ...definition } = item;
    out.push(
      `insert into public.claws (slug, name, family, foundation_id, summary, maturity, published, definition) values (${lit(item.slug)}, ${lit(item.name)}, ${lit(item.family)}, ${lit(item.foundation)}, ${lit(item.summary)}, ${lit(item.maturity)}, true, ${jsonLit(definition)}) on conflict (slug) do nothing;`,
    );
    for (const e of evidence) {
      out.push(
        `insert into public.claw_evidence (claw_slug, gate, ref, result, verified_at) values (${lit(item.slug)}, ${lit(e.gate)}, ${lit(e.ref)}, 'pass', ${lit(e.verifiedAt)}) on conflict (claw_slug, gate, ref) do nothing;`,
      );
    }
  }
  out.push("");
  return out.join("\n");
}
